<link rel='stylesheet' href='<?php echo $block->getViewFileUrl("Ziffity_Preorder::css/toggleButton.css") ?>' />
<script>
    require(['jquery', 'myscript'], function($, myscript) {
        myscript();
    });
</script>

<table class="chk_tbl">
    <tr>
        <td><b>Pre Order</b></td>
        <td>
            <!-- data-bind='checked: CheckVal' -->
            <label class="switch"> 
                <input type="checkbox" name="preOrderCheck" value="on">
                <span class="slider round"></span>
            </label>
        </td>
    </tr>
</table>

<div class="row" id="preOrderForm">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="preorderform/preorderform/submit"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Pre Order Form')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('First Name')) ?></span></label>
                            <div class="control">
                                <input name="fname" id="fname" title="First Name" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Last Name')) ?></span></label>
                            <div class="control">
                                <input name="lname" id="lname" title="Last Name" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Quantity')) ?></span></label>
                            <div class="control">
                                <input name="quantity" id="quantity" title="Quantity" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                                <input type="hidden" name="cdate" value="<?= date('Y-m-d'); ?>" id="cdate">
                                <input type="hidden" name="status" value="Pending" id="status">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Order Fields')) ?></span></label>
                            <div class="control">
                                <input name="order_field" id="order_field" title="Order Fields" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>

                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action submit primary" title="Submit"><span><?= $block->
                                    escapeHtmlAttr(__('submit')) ?></span></button>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            
        </form>
    </div>
</div>