<?php
$helper = $this->helper('Ziffity\Feedback\Helper\Data');
if ($helper->isLoggedIn()) 
{
    $om = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $om->create('Magento\Customer\Model\Session');
    if($customerSession->isLoggedIn()) {
        $sessFName = $customerSession->getCustomer()->getFirstname();
        $sessLName = $customerSession->getCustomer()->getLastname();
        $sessEmail = $customerSession->getCustomer()->getEmail();
    }
}

?>

<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $block->getFormAction() ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('First Name')) ?></span></label>
                            <div class="control">
                                <input name="fname" id="fname" title="First Name" value="<?php if($helper->isLoggedIn()) { echo $sessFName; } ?>" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Last Name')) ?></span></label>
                            <div class="control">
                                <input name="lname" id="lname" title="Last Name" value="<?php if($helper->isLoggedIn()) { echo $sessLName; } ?>" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="<?php if($helper->isLoggedIn()) { echo $sessEmail; } ?>" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                                <input type="hidden" name="storeemail" id="storeemail" value="<?php if($block->getStoreEmail()) { echo $block->getStoreEmail(); } ?>">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Comment')) ?></span></label>
                            <div class="control">
                                <textarea class="input-text" name="comment" id="comment" title="Comment" value="" data-validate="{required:true}"></textarea>
                                <input type="hidden" name="cdate" value="<?= date('Y-m-d'); ?>" id="cdate">
                                <input type="hidden" name="status" value="Pending" id="status">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>